/**
 * Each preset gives light-theme hex values only. Applying one feeds those
 * exact colors into the engine as "manual" identities (see SmartPaletteEngine),
 * so the matching dark-mode version is derived the same way any manual edit
 * is: same hue, relit for a dark background — not a second random guess.
 *
 * Values are each brand's commonly published primary marks, used here purely
 * as numeric starting points for a palette (not logos or other brand assets).
 */
export const PRESETS = [
  {
    id: "google",
    name: "Google",
    background: "#ffffff",
    text: "#202124",
    primary: "#4285f4",
    secondary: "#34a853",
    accent: "#ea4335",
  },
  {
    id: "microsoft",
    name: "Microsoft",
    background: "#ffffff",
    text: "#1b1a19",
    primary: "#0078d4",
    secondary: "#5c2d91",
    accent: "#d83b01",
  },
  {
    id: "adobe",
    name: "Adobe",
    background: "#ffffff",
    text: "#1e1e1e",
    primary: "#fa0f00",
    secondary: "#1473e6",
    accent: "#2d9d78",
  },
  {
    id: "amazon",
    name: "Amazon",
    background: "#ffffff",
    text: "#0f1111",
    primary: "#ff9900",
    secondary: "#232f3e",
    accent: "#146eb4",
  },
  {
    id: "apple",
    name: "Apple",
    background: "#fbfbfd",
    text: "#1d1d1f",
    primary: "#0071e3",
    secondary: "#1d1d1f",
    accent: "#ff3b30",
  },
  {
    id: "meta",
    name: "Meta",
    background: "#ffffff",
    text: "#050505",
    primary: "#0668e1",
    secondary: "#1877f2",
    accent: "#00c6ff",
  },
  {
    id: "netflix",
    name: "Netflix",
    background: "#141414",
    text: "#ffffff",
    primary: "#e50914",
    secondary: "#564d4d",
    accent: "#b81d24",
  },
  {
    id: "spotify",
    name: "Spotify",
    background: "#121212",
    text: "#ffffff",
    primary: "#1db954",
    secondary: "#1ed760",
    accent: "#2d46b9",
  },
  {
    id: "slack",
    name: "Slack",
    background: "#ffffff",
    text: "#1d1c1d",
    primary: "#4a154b",
    secondary: "#36c5f0",
    accent: "#2eb67d",
  },
  {
    id: "ibm",
    name: "IBM",
    background: "#ffffff",
    text: "#161616",
    primary: "#0f62fe",
    secondary: "#393939",
    accent: "#ff832b",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    background: "#ffffff",
    text: "#032d60",
    primary: "#00a1e0",
    secondary: "#1798c1",
    accent: "#ffb75d",
  },
  {
    id: "stripe",
    name: "Stripe",
    background: "#ffffff",
    text: "#0a2540",
    primary: "#635bff",
    secondary: "#0a2540",
    accent: "#00d4ff",
  },
  {
    id: "airbnb",
    name: "Airbnb",
    background: "#ffffff",
    text: "#222222",
    primary: "#ff5a5f",
    secondary: "#00a699",
    accent: "#fc642d",
  },
  {
    id: "x",
    name: "X (Twitter)",
    background: "#ffffff",
    text: "#0f1419",
    primary: "#1d9bf0",
    secondary: "#0f1419",
    accent: "#f91880",
  },
];
